neighborhoods = [
    'Downtown',
    'Strip District',
    'Mount Washington',
    'Shadyside',
    'South Oakland',
    'Allentown',
    'Squirrel Hill North',
    'South Shore',
    'Manchester',
    'Cultural District',
    'East Liberty',
    'Mexican War Streets',
    'Brighton Heights',
    'Beechview',
    'Northview Heights',
    'East Allegheny',
    'Perry North',
    'Stanton Heights',
    'Polish Hill',
    'South Side Flats',
    'Summerset at Frick Park',
    'Allegheny Center',
    'South Side Slopes',
    'Beltzhoover',
    'Sheraden',
    'Swisshelm Park',
    'Crafton Heights',
    'Banksville',
    'Bedford Dwellings',
    'Fineview',
    'Perry South',
    'Marshall-Shadeland',
    'North Shore',
    'Allegheny-West',
    'Duquesne Heights',
    'Fairywood',
    'Troy Hill',
    'California-Kirkbride',
    'Glen Hazel',
    'Point Breeze North',
    'New Homestead',
    'Esplen',
    'Spring Hill City View',
    'Homewood North',
    'Woods Run',
    'Upper Lawrenceville',
    'Central Northside',
    'Lower Lawrenceville',
    'Central Oakland',
    'West End',
]
